### ISSUE TITLE
Autodetect

### ISSUE THREAD

**Issue by Gyranthir** [zoltaroth/ragefireprices#1]
The autodetect in the current dist doesn't seem to work, I was able to fill in my own settings and it worked, but it was unable to locate the log files or my character name.

**Comment by nandor-code** [comment]
Did you give it the path to your EQ1 Log dir?  Auto detect rips through all the logs in the LogDir path and looks for anything matching eqlog_CHARACTER_ragefire.txt and then picks the newest one based on timestamp.  Can you paste what the app said in the console window?

**Comment by Gyranthir** [comment]
Once I updated the location of the log file everything worked. I have the
parser as a subfolder to my EQ folder, I didn't know if it would autodetect
from there or not.

**Comment by Gyranthir** [comment]
I also noticed it doesn't seem to be picking up some things like:

http://everquest.allakhazam.com/db/item.html?item=67320
http://everquest.allakhazam.com/db/item.html?item=2597
http://everquest.allakhazam.com/db/item.html?item=2323
http://everquest.allakhazam.com/db/item.html?item=1933

Does it have to be specifically linked in the chat or does it just parse
the text as text?

I see a lot of items and then when I try to go search them I get nothing.

So I am curious about how it's doing it and if there's a flaw.

**Comment by nandor-code** [comment]
You will have to talk to Orsenfelt about how the parsing happens.  This uploader just sends the data to the webservice which does all the parsing - I haven't seen that code myself.

**Comment by Gyranthir** [comment]
Ahhh ok.

**Comment by orsenfelt** [comment]
Didn't know there were issues sitting here, you've got me through email about this though so closing =)
